name: weather_prediction_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.12.10
  - pip
  - numpy==2.2.6
  - pandas==2.2.3
  - matplotlib==3.10.3
  - seaborn==0.13.2
  - scikit-learn==1.6.1
  - pip:
      - mlflow==2.22.0
      - python-dotenv==1.1.0
      - dagshub==0.5.10
      - mlflow_skinny==2.22.0
