name: Train Weather Model

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-24.04
    env:
      MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USER }}/${{ secrets.DAGSHUB_REPO }}.mlflow
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.12"
          miniconda-version: "latest"
          environment-file: MLProject/conda.yaml
          activate-environment: mlflow-env

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Install Python dependencies
        shell: bash -l {0}
        run: |
          conda activate mlflow-env
          pip install docker

      - name: Run MLflow project
        shell: bash -l {0}
        run: |
          conda activate mlflow-env
          mlflow run MLProject -P data_path=weather_preprocessed.csv

      - name: Build and Push Docker Image
        shell: bash -l {0}
        run: |
          conda activate mlflow-env

          # Get latest run ID
          RUN_ID=$(mlflow runs list --experiment-names "Weather_Prediction_CI" --max-results 1 | awk 'NR==2 {print $4}')
          echo "Using Run ID: $RUN_ID"

          # Build Docker image
          mlflow models build-docker -m "runs:/$RUN_ID/model" -n "weather-predictor"

          # Login to Docker Hub
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

          # Tag and push
          docker tag weather-predictor:latest ${{ secrets.DOCKERHUB_USERNAME }}/weather-predictor:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/weather-predictor:latest

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            mlruns/
            MLProject/
          retention-days: 5
